---
title: "DA_communitycomposition"
author: "Lieke"
date: "2024-06-20"
output: html_document
---

```{r packages}
# general
library(tidyverse)
# dissimilarity matrix, NMDS, PERMANOVA, PERMDISP
library(vegan)
# models
library(glmmTMB)
library(mgcv) 
# indicator species
library(indicspecies)
# visualisation
library(patchwork)
library(ggforce) # for NMDS amoebae
library(flextable)
library(gridExtra) # for grid.arrange
library(report)
library(fantaxtic)
library(cowplot)
library(ggnested)
landusetypes <- c("Food_forest", "Forest", "Grassland", "Arable_field")
```

```{r functions}
source("functions.R")
```

```{r data}

# original data
harvestmen_raw <- read.csv("Data/Harvestmen_P2.csv") %>%
  select(!c(Stage, Sex)) %>%
  as.data.frame() %>%
  # change from all caps to normal
  mutate(species = str_to_title(species))
dflist <- readRDS("dflist.rds")

# species abundance matrices (community data table)
specablist <- readRDS("specablist.rds")

# Bray-Curtis dissimilarity
dissimlist <- readRDS("dissimlist.rds")

# code info
codes_info <- read.csv("Data/codes_info.csv")

# taxonomic and forest affinity info
species_info <- read.csv("Data/species_info.csv")

# # read in NMDS results
# NMDSreslist <- readRDS("NMDSreslist.rds")
```

# NMDS

```{r NMDS}
# list to save plots in
NMDS_plots <- list()

# list to save results in
NMDSreslist <- list() # will be chill to have this saved instead of having to rerun nmds all the time

for(m in names(dissimlist)){
  df <- dissimlist[[m]]
    # remove croplands and grasslands
  set.seed(2983847)
  NMDS_res <- metaMDS(df, k = 2, trymax = 999, trace = FALSE) 
  # autotransform by default TRUE
  
  p <- myNMDS(df, NMDS_res, codes_info) + 
    # temporary for figure
    labs(x = "NMDS1", y = "NMDS2")
  
  NMDS_plots[[m]] <- p
  
  NMDSreslist[[m]] <- NMDS_res

}

saveRDS(NMDSreslist, "NMDSreslist.rds")
# (NMDSplot <- do.call("grid.arrange", c(NMDS_plots, ncol = 3)))
(NMDSplot <- do.call("plot_grid", c(NMDS_plots[c("df_trap", "df_sitesum")], ncol=2, align="hv")))

ggsave("NMDSplot.svg", NMDSplot, width = 16, height = 8)
ggsave("NMDSplotFOFF.svg", NMDS_plots[["df_sitesum_FOFF"]], width = 8, height = 8)

## if we only include communities with at least 5 individuals and only include land use types for which at least 6 observations remain, we can still make the comparison with forests, but not with grass- and croplands (check if at site level this would be remedied)

# NMDS_plots_sep <- list()
# 
# for(m in names(dissimlist)){
#   set.seed(2983847)
#   df <- as.matrix(dissimlist[[m]])
# 
#   rn <- data.frame(code = rownames(df)) %>%
#     left_join(codes_info %>% select(code, landuse, location))
#   
#   # count number of observations per land use type
#   n_obs <- rn %>%
#     group_by(landuse) %>%
#     summarise(n = n()) %>%
#     # now already remove land use type for which there are less than 6 observations
#     filter(n >= 6)
#   
#   # filter out rownames (and column names) of land use type with too few observations
#   rn <- rn %>%
#     filter(landuse %in% n_obs$landuse)
#   
#   df <- df[rn$code, rn$code]
# 
#     
#   p <- myNMDS(df, codes_info) + 
#     # temporary for figure
#     labs(x = "NMDS1", y = "NMDS2")
#   
#   NMDS_plots_sep[[m]] <- p
# 
# }
# 
# 
# 
# (NMDSplot_sep <- do.call("grid.arrange", c(NMDS_plots_sep, ncol = 3)))
# ggsave("NMDSplot_sep.svg", NMDSplot_sep, width = 16, height = 16)
```

# Indicator species

```{r indicspecies}

for(m in names(specablist)){
  set.seed(2983847)
  df <- (specablist[[m]])
  
  site_class <- data.frame(code = rownames(df)) %>%
    left_join(codes_info) %>%
    select(landuse)

indval <- multipatt(df, site_class$landuse, 
                    control = how(nperm=999)) 

#summary(indval) # for all three cases only Phalangium opilio associated with combination of grass- and cropland land use types
summary(indval, alpha = 0.1) # alpha = 1 to display all
}


```

# Taxonomy

Stacked bars with proportion of individuals belonging to certain taxonomic group.
This is in any case at the site level, not trap level, and taking the mean proportion per site or the proportion after having summed two traps per site gives exactly the same results (logically, but also tested it to be sure).

```{r taxonomy_bars_layout}
# colours
pal <- c("#0C7BDC", "#FFC20A","#40B0A6","#5D3A9B","#FEFE62","#DC3220","#1AFF1A","#D35FB7","#994F00","#88CCEE")

# theme
set_theme <- list(
  theme_bw(),
  theme(panel.grid = element_blank(),
        strip.background.x = element_blank(), 
        strip.placement = "outside",
        axis.line = element_line(),
        axis.text.x = element_blank(),
        axis.title.x = element_blank(),
        axis.ticks.x = element_blank(),
        axis.ticks.length.x = unit(0, "pt"),
        panel.border = element_blank(),
        panel.spacing.x = unit(7, "pt"), # does what it implies, space the panels of the facet 
        panel.grid.major.x = element_blank(),
        axis.text = element_text(size = 14),
        axis.title.y = element_text(size = 14),
        strip.text.x = element_text(size = 14))#,
        # legend.text = element_text(size = 13), 
        # legend.title = element_text(size = 14))
)

```

```{r taxonomy_bars}
tax_stack <- dflist[["df_sitesum"]] %>%
  filter(count > 0) %>%
  left_join(codes_info) %>%
  ungroup() %>%
  mutate(landuse = factor(landuse, levels = c("Food_forest", "Forest",
                                              "Grassland", "Arable_field" ))) %>%
  # add taxonomic information
  left_join(taxonomy) %>%
  ggnested(aes(x = code, y = count, main_group = family, sub_group = species), 
         main_palette = pal) +
  geom_col(position = position_fill(reverse = TRUE)) + 
  # 0 at level 0 of y axis
  scale_y_continuous(expand = expansion(mult = c(0, .05))) + #, labels = scales::percent
  # add padding around outer bars
  scale_x_discrete(expand = expansion(add = .8)) +
  labs(y = "Proportion of captured individuals",
       fill = "Genus") +
  facet_grid(.~ landuse, switch = "x", space = "free_x", scales = "free_x",
             labeller = labeller(landuse = c("Food_forest" = "Food forest",
                                             "Forest" = "Forest",
                                             "Grassland" = "Grassland",
                                             "Arable_field" = "Cropland"))) +
  guides(fill = guide_legend(ncol = 1)) + # number of columns for legend
  set_theme +
  theme(legend.position = "right")

ggsave("tax_stack.png")
```

# Species table

```{r speciestable}

# averaged across sessions (still need to fix this, sum per species, now multiple rows per species)
# tbl <- dflist[["df_sitesum"]] %>% 
#   # here count is the average of the four or three sessions
#   # could also opt for displaying total number of individuals, not averaged?
#   # but this is also because perhaps bias in land use types in terms of visitation session 4?
#   left_join(codes_info) %>%
#   filter(count > 0) %>%
#   mutate(landuse = factor(landuse, levels = c("Food_forest", "Forest", 
#                                               "Grassland", "Arable_field" ))) %>%
#   ungroup() %>%
#   pivot_wider(names_from = landuse,
#               values_from = count) %>%
#   replace_na(list(Food_forest = 0, Forest = 0, Grassland = 0, Arable_field = 0)) %>%
#   mutate(Total = rowSums(across(where(is.numeric)))) %>%
#   # round
#   left_join(species_info) %>%
#   arrange(family) %>%
#   select(species, family, 
#          forest_affinity, 
#          #IUCN_BE, IUCN_NL, # may still look for this, but likely doesn't exist
#          Food_forest, Forest, Grassland, Arable_field, Total) %>%
#   # cleaner presentation of strings
#   mutate(species = gsub("_", " ", species)) %>%
#   rename("Species" = "species",
#          "Affinity to forests" = "forest_affinity",
#          "Food forest" = "Food_forest",
#          "Cropland" = "Arable_field",
#          )


# not averaged across sessions 
tbl_total <- readRDS("harvestmen.rds") %>%
  left_join(codes_info %>% select(site, location, landuse) %>% distinct()) %>%
  # sum all counts per species per land use type
  group_by(landuse, species) %>%
  summarise(count = sum(abundance)) %>%
  mutate(landuse = factor(landuse, levels = c("Food_forest", "Forest", 
                                              "Grassland", "Arable_field" ))) %>%
  ungroup() %>%
  pivot_wider(names_from = landuse,
              values_from = count) %>%
  replace_na(list(Food_forest = 0, Forest = 0, Grassland = 0, Arable_field = 0)) %>%
  mutate(Total = rowSums(across(where(is.numeric)))) %>%
  left_join(species_info) %>%
  arrange(family) %>%
  select(species, family, 
         forest_affinity, 
         #IUCN_BE, IUCN_NL, # may still look for this, but likely doesn't exist
         Food_forest, Forest, Grassland, Arable_field, Total) %>%
  # cleaner presentation of strings
  mutate(species = gsub("_", " ", species)) %>%
  rename("Species" = "species",
         "Affinity to forests" = "forest_affinity",
         "Food forest" = "Food_forest",
         "Cropland" = "Arable_field",
         )
  
  
# save as csv
write.csv(tbl_total, "speciestable_total.csv")
```

<!--
## PERMDISP and PERMANOVA

### 3 betadispers

```{r PERMDISP}
# first for groups considered in main (pooled microarthropods and pooled macroarthropods)
# but also for separate groups

betadisper_output <- data.frame()
dmlist <- dmlist[grouporder_total]

for(m in names(dmlist)){
  set.seed(2983847)
  df <- as.matrix(dmlist[[m]])
  rn <- data.frame(code = rownames(df)) %>%
    left_join(codes_info %>% select(code, landuse, location))
  
  n_obs <- rn %>%
    group_by(landuse) %>%
    summarise(n = n()) %>%
    # now already remove land use type for which there are less than 6 observations
    filter(n >= 6)

  for(l in setdiff(n_obs$landuse, "Food_forest")){ # only for those reference land use types with >= 6 obs.
    dissim <- rn %>%
        filter(landuse %in% c("Food_forest",l)) %>%
        pull(code) %>%
      { df[.,.] } %>%
      as.dist()
    dissim_info <- rn %>% filter(landuse=="Food_forest"|landuse==l)
    disper_lu <- betadisper(dissim, dissim_info$landuse, type="centroid")
    FF <- round(disper_lu$group.distances[["Food_forest"]], digits=2)
    CON <- round(disper_lu$group.distances[[l]], digits=2)
    F_lu <- format(round(permutest(disper_lu)$tab$`F`[1], 
                         digits = 1))
    p_lu <- p.adjust(permutest(disper_lu)$tab$`Pr(>F)`[1],
                     method="holm", n = nrow(n_obs) - 1) # the number of comparisons made (FF vs ...)
    disper_loc <- betadisper(dissim, dissim_info$location, type="centroid")
    F_loc <- round(permutest(disper_loc)$tab$`F`[1], digits = 1)
    p_loc <- p.adjust(permutest(disper_loc)$tab$`Pr(>F)`[1], 
                      method="holm", n = nrow(n_obs) - 1) # idem above
    
    output <- cbind(group = m, 
                    contrast = l,
                    n_FF = n_obs %>% filter(landuse == "Food_forest") %>% pull(),
                    n_CON = n_obs %>% filter(landuse == l) %>% pull(),
                    F_loc, p_loc, FF, CON, F_lu, p_lu
                    )
    betadisper_output <- rbind(betadisper_output, output)
      }
}


flextable(betadisper_output)
write.csv(betadisper_output, "PERMDISP_output.csv")
```

Based on the results of the PERMDISP, we can perform all PERMANOVAs for the main groups. In a few cases there is the combination of a difference in the number of observations and dispersion between the two land use types, but then the dispersion is always greater in the group with the highest number of observations (FF), so there is a conservative bias, and yet we still detect differences, so OK; see supplement.

For the separate arthropod groups, there was never a statistically clear difference in dispersion between FF and the reference land use type, so all according separate PERMANOVAs can be conducted.

### 3 permanovas

```{r PERMANOVA}
permanova_output <- data.frame()

for(m in names(dmlist)){
  set.seed(2983847)
  df <- as.matrix(dmlist[[m]])
  rn <- data.frame(code = rownames(as.matrix(df))) %>%
    left_join(codes_info %>% select(code, landuse, location))
  
  n_obs <- rn %>%
    group_by(landuse) %>%
    summarise(n = n()) %>%
    # now already remove land use type for which there are less than 6 observations
    filter(n >= 6)

  for(l in setdiff(n_obs$landuse, "Food_forest")){ # only for those reference land use types with >= 6 obs.
      dissim <- rn %>%
          filter(landuse %in% c("Food_forest",l)) %>%
          pull(code) %>%
            { df[.,.] }
      dissim_info <- rn %>% filter(landuse=="Food_forest"|landuse==l)
      
      results <- adonis2(dissim ~ location + landuse, 
                          data = dissim_info, by="terms")
      
      results_loc <- results[1,] %>%
        rename("p" = "Pr(>F)",
               "pseudo_F" = "F") %>%
        mutate(df = paste0(Df, ", ", results[4,1]),
               p_adj = p.adjust(p, method = "holm", n = nrow(n_obs) - 1)) %>%
        select(df, pseudo_F, p_adj, R2)
      
      results_lu <- results[2,] %>%
        rename("p" = "Pr(>F)",
               "pseudo_F" = "F") %>%
        mutate(df = paste0(Df, ", ", results[4,1]),
               p_adj = p.adjust(p, method = "holm", n = nrow(n_obs) - 1)) %>%
        select(df, pseudo_F, p_adj, R2)
      
      output <- rbind(results_loc, results_lu) %>%
        rownames_to_column("term") %>%
        mutate(group = m,
               contrast = l,
               .before = "term")
      
      permanova_output <- rbind(permanova_output, round_df(output,digits=3))

    }
  
}
 
flextable(permanova_output)
write.csv(permanova_output, "PERMANOVA_output.csv")
```
-->
